config/routes.rb
Rails.application.routes.draw do
  get 'assigned', to: 'projects#assigned', as: 'assigned_projects'
  devise_for :users
  root "projects#index"
  resources :projects do
    # helps to assign projects to users
    # TODO apps routes should
    put 'assign_user', on: :member
    resources :todos, except: [:show, :index] do
      member do
        patch :complete
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  has_many :todos, dependent: :destroy
  belongs_to :user
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  
  belongs_to :project
  belongs_to :user

  def completed?
    !completed_at.nil?
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        
        
  has_many :todos
  has_many :projects


  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy assign_user ]
  before_action :verify_user, only: %i[ edit update destroy show ]
  def index
    @projects = current_user.projects.all.order('Created_at DESC')
  end

  def show
    @todos = @project.todos.all.order('Created_at DESC')
    @users = User.where.not(id: current_user.id)
  end

  def assigned
    @projects = Project.where(assigned_by: current_user.id, assigned_status: true).order(created_at: :desc)
  end

  def assign_user
    selected_user_id = params[:selected_user]
    selected_user_email = User.find(selected_user_id).email
    if @project.update(user_id: selected_user_id, assigned_status: true)
      flash[:success] = "Project assigned to the #{selected_user_email.split('@')[0].capitalize! }"
    else
      flash[:error] = "Failed to assign the project to the selected user."
    end
    redirect_to root_path
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.turbo_stream { flash.now[:notice] = "Project was successfully created." }
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.turbo_stream { flash.now[:notice] = "Project was successfully updated." }
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy!

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Project was successfully destroyed." }
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :user_id, :assigned_by, :assigned_status)
    end

    def verify_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to root_path,alert: "Not Authorized!" if @project.nil?
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_project
  before_action :set_todos, only: [:edit, :update, :destroy]
    def new
      @todo = @project.todos.build
    end
  
    def edit
    end
    
    def show
      @todo = current_user.todos.find(params[:id])
    end
  
    def update
      if @todo.update(todo_params)
        respond_to do |format|
          format.html { redirect_to root_path, notice: "Todo was successfully updated." }
          format.turbo_stream { flash.now[:notice] = "Todo was successfully updated." }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
      @todos = @project.todos.all
      @todo = @project.todos.build(todo_params)
  
      if @todo.save
        respond_to do |format|
          format.html { redirect_to root_path, notice: "Todo was successfully created." }
          format.turbo_stream { flash.now[:notice] = "Todo was successfully created." }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @todo.destroy
      @todos = @project.todos.all
    
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Todo was successfully destroyed." }
        format.turbo_stream { flash.now[:notice] = "Todo was successfully destroyed." }
      end
    end

    def complete

      @todo = @project.todos.find(params[:id])
      @todos = @project.todos.all
  
      if @todo.update(completed_at: Time.now)
        respond_to do |format|
          format.turbo_stream { flash.now[:notice] = "Todo marked as completed!"}
          format.html { redirect_to project_path(@project) }
        end
      else
      end
    end
    
    private
  
    def todo_params
      params.require(:todo).permit(:title, :description, :user_id)
    end
  
    def set_todos
      @todo = @project.todos.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= turbo_frame_tag "remote_modal" %>
    <div id="alert">
      <%= render "projects/flash" %>
    </div>
    <div class="container mt-5">
      <div class="card p-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message " data-controller="flash-messages">
    <%= message %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: @project) do |form| %>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id,id: 'todo_user_id',class: 'form-control mt-2' %>
    <%= form.hidden_field :assigned_by, value: current_user.id,id: 'assigned_user_id',class: 'form-control mt-2' %>
    <%= form.hidden_field :assigned_status %>
    <%= form.label :title, style: 'color: white;' %>
    <%= form.text_field :title, class: "form-control", placeholder: 'Enter title for your project.....' %>
    <% if @project.errors.any? %>
      <div class="text">
        <% @project.errors.full_messages_for(:title).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-success mt-2', data: { action: 'click->bootstrap#submitEnd'} %>
    <%= link_to 'Cancel', root_path, class: 'btn btn-outline-white mt-2'%>
  </div>
<% end %>

app/views/projects/_form_modal.html.erb
<%= turbo_frame_tag "remote_modal", target: '_top' do %>
  <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" data-controller="bootstrap">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title fs-5" id="staticBackdropLabel" style="color: white;"><%= modal_title %> </h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: white !important;"></button>
        </div>
        <div class="modal-body">
          <%= render form_partial %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_frame_tag project do %>
  <hr>
  <div class="d-flex justify-content-between">
    <div class="titles">
      <h1 class="fw-normal"><%= link_to project.title , project, data: { turbo_frame: '_top'} %></h1>
      <p> Created: <%= time_ago_in_words(project.created_at) + ' ago'%>  | <%= project.todos.count %> Todo's  </p>
      <% if project.assigned_status %>
        <p> Assigned by: <b><%= User.find(project.assigned_by).email %></b></p>
      <% end %>
    </div>
    <div class="d-flex gap-1">
      <p><%= link_to edit_project_path(project), data: { controller: 'bs-modal' }, class: 'btn btn-success' do %>
          <i class="bi bi-pen"></i>
        <% end %>
      </p>
      <p><%= button_to  project_path(project), method: :delete, class: 'btn btn-danger' do%>
          <i class="bi bi-trash"></i>
        <%end %>
      </p>
    </div>
  </div>
  <hr>
<% end %>

app/views/projects/assigned.html.erb
<div class="container">
  <% if @projects.present? %>
    <h1>
      Assigned Todos <small> (<%= current_user.email %>)</small>
    </h1>
    <hr>
    <% @projects.each do |x| %>
      <h3><%= link_to x.title, project_path(x) %></h3>
      <p>Assigned to: <%= x.user.email %></p>
      <% x.todos.each do |todo| %>
        <% if todo.completed? %>
          <p><%= todo.title %> <span class="badge rounded-pill text-bg-success">Completed</span></p>
        <% else %>
          <p><%= todo.title %> <span class="badge rounded-pill text-bg-danger">Not Completed</span></p>
        <% end %>
      <% end %>
      <hr>
    <% end %>
    <%= link_to 'Return Home', root_path, class: 'btn btn-primary mt-2'%>
  <% else %>
    <div class="text-center">
      <h3 class="text-muted" style="color: white !important;">No Todo's Assigned till date!</h3>
      <%= link_to 'Return Home', root_path, class: 'btn btn-primary mt-2'%>
    </div>
  <% end %>
</div>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.prepend "projects" do %>
  <%= render 'projects/project', project: @project %>
<% end %>
<%= turbo_stream.update Project.new, ''%>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>

app/views/projects/destroy.turbo_stream.erb
<%= turbo_stream.remove @project %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>

app/views/projects/edit.html.erb
<%= turbo_frame_tag @project do %>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'projects/form_modal', modal_title: 'Edit your todo!', form_partial: 'projects/form' %>
<% end %>

app/views/projects/index.html.erb
<div class="d-flex gap-4 justify-content-center text-align-center">
  <h1>Projects </h1>
  <%= link_to new_project_path, data: { controller: 'bs-modal' }, title: "Add New Project" do %>
    <i class="bi bi-plus-square-fill" style="font-size: 2em;"></i>
  <% end %>
</div>
<%= turbo_frame_tag Project.new%>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
  <% end %>
  <div class="text-end d-flex justify-content-end flex-column">
    <i class="bi bi-person">  <%= current_user.email.split('@')[0].capitalize! %>  |  <%= link_to 'Assigned', assigned_projects_path %></i>
    <%= button_to destroy_user_session_path, method: :delete, class: 'btn btn-danger' do %>
      <i class="bi bi-box-arrow-right"></i>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>
<%= turbo_frame_tag @project do %>
  <div class="mt-3">
    <%= render "form", project: @project %>
  </div>
<% end %>
<br>
<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'projects/form_modal', modal_title: 'Add a Project!', form_partial: 'projects/form' %>
<% end %>

app/views/projects/show.html.erb
<%= link_to root_path do %>
  <i class="bi bi-arrow-left h3"></i>
<% end %>
<div class="text-center">
  <h1><%= @project.title %></h1>
  <small>
    Created: <%= time_ago_in_words(@project.created_at) + ' ago'%>
  </small>
  <% if @todos.present? && User.count > 1 && !@project.assigned_status %>
    <p class="d-flex">
      <%= form_tag assign_user_project_path, method: :put do %>
        <div class="field">
          <%= select_tag :selected_user, options_for_select(@users.pluck(:email, :id)), prompt: 'Assign User', class: 'dropdown-icon p-1' %>
          <%= submit_tag 'Submit', class: 'btn btn-success btn-sm' %>
        </div>
      <% end %>
    </p>
  <% end %>
</div>
<main class="container">
  <div class="header">
    <div class="d-flex justify-content-between align-items-center border p-5 mt-4">
      <h1>Add Todo</h1>
      <%= link_to new_project_todo_path(@project), class: "btn display-1 btn-block", data: { controller: 'bs-modal' } do %>
        <i class="bi bi-plus-square-fill" style="font-size: 2em;"></i>
      <% end %>
    </div>
    <hr>
    <%= turbo_frame_tag Todo.new %>
    <%= turbo_frame_tag "todos" do %>
      <%= render @todos, project: @project %>
    <% end %>
    <%= render 'todos/progressbar',todos: @todos %>
  </div>
</main>

app/views/projects/update.turbo_stream.erb
<%= turbo_stream.update @project do %>
  <%= render 'projects/project', project: @project%>
<% end %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>

app/views/todos/_form.html.erb
<%= form_with(model: [@todo.project, @todo]) do |form| %>
  <div>
    <%= form.label :title, style: 'color: white' %>
    <%= form.text_field :title, class: 'form-control' %>
    <% if @todo.errors.any? %>
      <div class="text">
        <% @todo.errors.full_messages_for(:title).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :description, style: 'color: white' %>
    <%= form.text_field :description, class: 'form-control' %>
    <% if @todo.errors.any? %>
      <div class="text">
        <% @todo.errors.full_messages_for(:description).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="mt-3">
    <%= form.hidden_field :user_id, value: current_user.id,id: 'todo_user_id',class: 'form-control mt-2' %>
    <%= form.hidden_field :project_id %>
    <% if @todo.errors.any? %>
      <div class="text">
        <% @todo.errors.full_messages_for(:project_id).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-success', data: { action: 'click->bootstrap#submitEnd'}%>
  </div>
<% end %>

app/views/todos/_progressbar.html.erb
    
<div id="todo-list">
  <div class="progress" data-controller="progress" data-progress-total-todos="<%= todos.count %>" data-progress-completed-count="<%= todos.count { |x| x.completed? } %>">
    <div id="progressBar" class="progress-bar  progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div id="todo">
    <div class="d-flex justify-content-between">
      <div class="header flex-column">
        <h2 class="<%= todo.completed? ? "text-decoration-line-through" : "" %>" style="color: white !important;"><%= todo.title%></h2>
        <% if !todo.completed? %>
          <p class="text-muted" style="color: white !important;">
            <%= todo.description%>
          </p>
        <% else %>
          <p class="text-muted" style="color: white !important;">
            Completed: <%= time_ago_in_words(todo.completed_at)+ ' ago'%>
          </p>
        <% end %>
      </div>
      <div class="buttons">
        <%= button_to [project, todo],
                    method: :delete,
                    class: "btn btn-danger" do %>
          <i class="bi bi-trash"></i>
        <% end %>
        <% unless todo.completed? %>
          <%= link_to [:edit, project, todo],
                  class: "btn btn-success mt-1", data: { controller: 'bs-modal' } do %>
            <i class="bi bi-pen"></i>
          <% end%>
          <p>
            <%= link_to complete_project_todo_path(project, todo), data: { 'turbo-method': :patch },class: "btn btn-success mt-1", method: :patch do  %>
              <i class="bi bi-check2-all"></i>
            <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
<% end %>

app/views/todos/complete.turbo_stream.erb
<%= turbo_stream.update @todo do %>
  <%= render 'todos/todo', todo: @todo, project: @project %>
<% end %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>
<%= turbo_stream.update "todo-list" do %>
  <%= render 'todos/progressbar',  todos: @todos %>
<% end %>

app/views/todos/create.turbo_stream.erb
  <%= turbo_stream.prepend "todos" do %>
  <%= render @todo, todo: @todo, project: @project %>
<% end %>
<%= turbo_stream.update Todo.new, "" %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>
<%= turbo_stream.replace "todo-list" do %>
  <%= render 'todos/progressbar',  todos: @todos %>
<% end %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>
<%= turbo_stream.update "todo-list" do %>
  <%= render 'todos/progressbar',  todos: @todos %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag @todo do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'projects/form_modal', modal_title: 'Edit your todo!', form_partial: 'todos/form' %>
<% end %>

app/views/todos/new.html.erb
<%= turbo_frame_tag @todo do %>
  <div class="mb-3">
    <%= render "form", todo: @todo %>
    <hr>
  </div>
<% end %>

app/views/todos/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'projects/form_modal', modal_title: 'Add new todo!', form_partial: 'todos/form', todo: @todo %>
<% end %>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.update @todo do %>
  <%= render 'todos/todo', todo: @todo, project: @project %>
<% end %>
<%= turbo_stream.prepend "alert", partial: "projects/flash" %>